_target_: watchmal.loss.uncertainty_loss.UncertaintyLoss

task_losses:
  positions:
    _target_: watchmal.loss.position_huber.PositionHuberLoss
    delta: 0.004                       
  directions:
    _target_: watchmal.loss.direction_huber.DirectionHuberLoss 
    delta: 0.04
  energies:
    _target_: watchmal.loss.relative_huber.RelativeHuberLoss
    delta: 0.03    
    
initial_variances:
    positions: 4.631052433978766e-05
    directions: 0.0006307574221864343
    energies: 0.0006280846428126097
